#define K_MAX_SIZE 1000
#define K_ADMIN '1'
#define K_NUSER '2'
#define K_HOST_PORT 8081
#define K_HOST_IP INADDR_ANY
// #define K_HOST_IP "192.168.159.72"
#define K_BACKLOG 20
#define K_ADMIN_ID "053"
#define K_ADMIN_PASSWORD "lax"
#define K_LOGIN_FILE "is_logged_in"
#define K_ACC_ID_CNT "account_id_count"
#define K_CUST_ID_CNT "customer_id_count"
#define K_TRANS_ID_CNT "transaction_id_count"
#define K_CUST_RCD "customerRecords"
#define K_TRANS_RCD "transactionRecords"
#define K_ACC_RCD "accountRecords"
#define K_LOGGED_IN '1'
#define K_LOGGED_OUT '0'
#define K_MAX_TRANSACTIONS 5
#define SKIP_MESSAGE "$"
#define ERROR_MESSAGE "@"
#define HIDE_MESSAGE "*"
#define WITHDRAW 1
#define DEPOSIT 0
#define K_SIZE 100
#define SPACE 30
