#define K_ENTER_LOGIN "Enter login id:\n"
#define K_ENTER_PWD "Enter password:\n"
#define K_ENTER_NAME "Enter name:\n"
#define K_ENTER_AGE "Enter age:\n"
#define K_ENTER_GENDER "Enter gender(M/F/O):\n"
#define K_ENTER_ACC_NO "Enter account no.:\n"
#define K_ENTER_CUST_ID "Enter customer id.:\n"
#define K_ENTER_AMT "Enter amount:\n"
#define K_ENTER_OLD_PWD "Enter old password:\n"
#define K_ENTER_NEW_PWD "Enter new password:\n"

#define K_CHANGE_NAME "Do you want to change your name?(Y/N)\n"
#define K_CHANGE_AGE "Do you want to change your age?(Y/N)\n"
#define K_CHANGE_GENDER "Do you want to change your gender?(Y/N)\n"
#define K_CONFIRM "Do you confirm to make the above changes?(Y/N)\n"
#define K_CONFIRM_NEW_PWD "Confirm new password:\n"

#define K_USER_PAGE "\n\nUSER HOME PAGE\n\nPlease select \n1. Deposit \n2. Withdraw \n3. Balance enquiry \n4. Password change \n5. View details \n6. Logout\n"
#define K_ADMIN_PAGE "\n\nADMIN HOME PAGE\n\nPlease select \n1. Get transaction details \n2. Get all bank account details \n3. Create new customer account \n4. Delete customer account \n5. Modify Account \n6. Get Customer details \n7. Logout\n"
#define K_ACC_TYPE "Enter \n1. Single Account \n2. Joint Account\n"
#define K_USER_TYPE "Enter \n1. ADMIN \n2. Customer \n3. Exit\n"

#define K_ERROR_PWD_NOT_MATCHING "Passwords not matching!\n"
#define K_ERROR_INCORRECT_PWD "Incorrect password!\n"
#define K_PWD_UPDATED "Password udpated!\n"
#define K_INCORRECT_OPT "Please enter correct option!"
#define K_EXIT "THANK YOU FOR USING OUR BANK!"
#define K_DUMMY "dummy"